Introduce retries for release asset uploading

diff --git a/.github/workflows/build_and_deploy.yml b/.github/workflows/build_and_deploy.yml
--- a/.github/workflows/build_and_deploy.yml
+++ b/.github/workflows/build_and_deploy.yml
@@ -371,8 +371,20 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           mv $GITHUB_WORKSPACE/artifacts/linux/QEverCloudGenerator.zip /tmp/QEverCloudGenerator_linux_x86_64.zip
-          gh release upload --clobber continuous-master /tmp/QEverCloudGenerator_linux_x86_64.zip -R d1vanov/QEverCloudGenerator
+          for i in 0..3
+          do
+            export UPLOADED=0
+            gh release upload --clobber continuous-master /tmp/QEverCloudGenerator_linux_x86_64.zip -R d1vanov/QEverCloudGenerator && export UPLOADED=1 || true
+            if [ "$UPLOADED" = "1" ]; then
+              break
+            fi
+          done
+          if [ "$UPLOADED" != "1" ]; then
+            echo "Failed to upload artifact to release"
+            exit 1
+          fi
         if: ${{ github.ref == 'refs/heads/master' }}
+        shell: bash
 
       - name: Upload Linux artifact to continuous development release
         id: upload_linux_artifact_to_continuous_development_release
@@ -380,8 +392,20 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           mv $GITHUB_WORKSPACE/artifacts/linux/QEverCloudGenerator.zip /tmp/QEverCloudGenerator_linux_x86_64.zip
-          gh release upload --clobber continuous-development /tmp/QEverCloudGenerator_linux_x86_64.zip -R d1vanov/QEverCloudGenerator
+          for i in 0..3
+          do
+            export UPLOADED=0
+            gh release upload --clobber continuous-development /tmp/QEverCloudGenerator_linux_x86_64.zip -R d1vanov/QEverCloudGenerator && export UPLOADED=1 || true
+            if [ "$UPLOADED" = "1" ]; then
+              break
+            fi
+          done
+          if [ "$UPLOADED" != "1" ]; then
+            echo "Failed to upload artifact to release"
+            exit 1
+          fi
         if: ${{ github.ref == 'refs/heads/development' }}
+        shell: bash
 
       - name: Upload macOS artifact to continuous master release
         id: upload_macos_artifact_to_continuous_master_release
@@ -389,8 +413,20 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           mv $GITHUB_WORKSPACE/artifacts/macos/QEverCloudGenerator.zip /tmp/QEverCloudGenerator_macos_x86_64.zip
-          gh release upload --clobber continuous-master /tmp/QEverCloudGenerator_macos_x86_64.zip -R d1vanov/QEverCloudGenerator
+          for i in 0..3
+          do
+            export UPLOADED=0
+            gh release upload --clobber continuous-master /tmp/QEverCloudGenerator_macos_x86_64.zip -R d1vanov/QEverCloudGenerator && export UPLOADED=1 || true
+            if [ "$UPLOADED" = "1" ]; then
+              break
+            fi
+          done
+          if [ "$UPLOADED" != "1" ]; then
+            echo "Failed to upload artifact to release"
+            exit 1
+          fi
         if: ${{ github.ref == 'refs/heads/master' }}
+        shell: bash
 
       - name: Upload macOS artifact to continuous development release
         id: upload_macos_artifact_to_continuous_development_release
@@ -398,8 +434,20 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           mv $GITHUB_WORKSPACE/artifacts/macos/QEverCloudGenerator.zip /tmp/QEverCloudGenerator_macos_x86_64.zip
-          gh release upload --clobber continuous-development /tmp/QEverCloudGenerator_macos_x86_64.zip -R d1vanov/QEverCloudGenerator
+          for i in 0..3
+          do
+            export UPLOADED=0
+            gh release upload --clobber continuous-development /tmp/QEverCloudGenerator_macos_x86_64.zip -R d1vanov/QEverCloudGenerator && export UPLOADED=1 || true
+            if [ "$UPLOADED" = "1" ]; then
+              break
+            fi
+          done
+          if [ "$UPLOADED" != "1" ]; then
+            echo "Failed to upload artifact to release"
+            exit 1
+          fi
         if: ${{ github.ref == 'refs/heads/development' }}
+        shell: bash
 
       - name: Upload Windows x86 artifact to continuous master release
         id: upload_windows_x86_artifact_to_continuous_master_release
@@ -407,8 +455,20 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           mv $GITHUB_WORKSPACE/artifacts/windows/x86/QEverCloudGenerator.zip /tmp/QEverCloudGenerator_windows_x86.zip
-          gh release upload --clobber continuous-master /tmp/QEverCloudGenerator_windows_x86.zip -R d1vanov/QEverCloudGenerator
+          for i in 0..3
+          do
+            export UPLOADED=0
+            gh release upload --clobber continuous-master /tmp/QEverCloudGenerator_windows_x86.zip -R d1vanov/QEverCloudGenerator && export UPLOADED=1 || true
+            if [ "$UPLOADED" = "1" ]; then
+              break
+            fi
+          done
+          if [ "$UPLOADED" != "1" ]; then
+            echo "Failed to upload artifact to release"
+            exit 1
+          fi
         if: ${{ github.ref == 'refs/heads/master' }}
+        shell: bash
 
       - name: Upload Windows x86 artifact to continuous development release
         id: upload_windows_x86_artifact_to_continuous_development_release
@@ -416,8 +476,20 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           mv $GITHUB_WORKSPACE/artifacts/windows/x86/QEverCloudGenerator.zip /tmp/QEverCloudGenerator_windows_x86.zip
-          gh release upload --clobber continuous-development /tmp/QEverCloudGenerator_windows_x86.zip -R d1vanov/QEverCloudGenerator
+          for i in 0..3
+          do
+            export UPLOADED=0
+            gh release upload --clobber continuous-development /tmp/QEverCloudGenerator_windows_x86.zip -R d1vanov/QEverCloudGenerator && export UPLOADED=1 || true
+            if [ "$UPLOADED" = "1" ]; then
+              break
+            fi
+          done
+          if [ "$UPLOADED" != "1" ]; then
+            echo "Failed to upload artifact to release"
+            exit 1
+          fi
         if: ${{ github.ref == 'refs/heads/development' }}
+        shell: bash
 
       - name: Upload Windows x64 artifact to continuous master release
         id: upload_windows_x64_artifact_to_continuous_master_release
@@ -425,8 +497,20 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           mv $GITHUB_WORKSPACE/artifacts/windows/x64/QEverCloudGenerator.zip /tmp/QEverCloudGenerator_windows_x64.zip
-          gh release upload --clobber continuous-master /tmp/QEverCloudGenerator_windows_x64.zip -R d1vanov/QEverCloudGenerator
+          for i in 0..3
+          do
+            export UPLOADED=0
+            gh release upload --clobber continuous-master /tmp/QEverCloudGenerator_windows_x64.zip -R d1vanov/QEverCloudGenerator && export UPLOADED=1 || true
+            if [ "$UPLOADED" = "1" ]; then
+              break
+            fi
+          done
+          if [ "$UPLOADED" != "1" ]; then
+            echo "Failed to upload artifact to release"
+            exit 1
+          fi
         if: ${{ github.ref == 'refs/heads/master' }}
+        shell: bash
 
       - name: Upload Windows x64 artifact to continuous development release
         id: upload_windows_x64_artifact_to_continuous_development_release
@@ -434,8 +518,20 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           mv $GITHUB_WORKSPACE/artifacts/windows/x64/QEverCloudGenerator.zip /tmp/QEverCloudGenerator_windows_x64.zip
-          gh release upload --clobber continuous-development /tmp/QEverCloudGenerator_windows_x64.zip -R d1vanov/QEverCloudGenerator
+          for i in 0..3
+          do
+            export UPLOADED=0
+            gh release upload --clobber continuous-development /tmp/QEverCloudGenerator_windows_x64.zip -R d1vanov/QEverCloudGenerator && export UPLOADED=1 || true
+            if [ "$UPLOADED" = "1" ]; then
+              break
+            fi
+          done
+          if [ "$UPLOADED" != "1" ]; then
+            echo "Failed to upload artifact to release"
+            exit 1
+          fi
         if: ${{ github.ref == 'refs/heads/development' }}
+        shell: bash
 
       - name: Upload Linux artifact to tagged release
         id: upload_linux_artifact_to_tagged_release
@@ -444,8 +540,20 @@ jobs:
         run: |
           export TAG_NAME=$(echo $GITHUB_REF | sed 's/.*\/\(.*\)$/\1/')
           mv $GITHUB_WORKSPACE/artifacts/linux/QEverCloudGenerator.zip /tmp/QEverCloudGenerator_linux_x86_64.zip
-          gh release upload --clobber ${TAG_NAME} /tmp/QEverCloudGenerator_linux_x86_64.zip -R d1vanov/QEverCloudGenerator
+          for i in 0..3
+          do
+            export UPLOADED=0
+            gh release upload --clobber ${TAG_NAME} /tmp/QEverCloudGenerator_linux_x86_64.zip -R d1vanov/QEverCloudGenerator && export UPLOADED=1 || true
+            if [ "$UPLOADED" = "1" ]; then
+              break
+            fi
+          done
+          if [ "$UPLOADED" != "1" ]; then
+            echo "Failed to upload artifact to release"
+            exit 1
+          fi
         if: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/development' }}
+        shell: bash
 
       - name: Upload macOS artifact to tagged release
         id: upload_macos_artifact_to_tagged_release
@@ -454,8 +562,20 @@ jobs:
         run: |
           export TAG_NAME=$(echo $GITHUB_REF | sed 's/.*\/\(.*\)$/\1/')
           mv $GITHUB_WORKSPACE/artifacts/macos/QEverCloudGenerator.zip /tmp/QEverCloudGenerator_macos_x86_64.zip
-          gh release upload --clobber ${TAG_NAME} /tmp/QEverCloudGenerator_macos_x86_64.zip -R d1vanov/QEverCloudGenerator
+          for i in 0..3
+          do
+            export UPLOADED=0
+            gh release upload --clobber ${TAG_NAME} /tmp/QEverCloudGenerator_macos_x86_64.zip -R d1vanov/QEverCloudGenerator && export UPLOADED=1 || true
+            if [ "$UPLOADED" = "1" ]; then
+              break
+            fi
+          done
+          if [ "$UPLOADED" != "1" ]; then
+            echo "Failed to upload artifact to release"
+            exit 1
+          fi
         if: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/development' }}
+        shell: bash
 
       - name: Upload Windows x86 artifact to tagged release
         id: upload_windows_x86_artifact_to_tagged_release
@@ -464,8 +584,20 @@ jobs:
         run: |
           export TAG_NAME=$(echo $GITHUB_REF | sed 's/.*\/\(.*\)$/\1/')
           mv $GITHUB_WORKSPACE/artifacts/windows/x86/QEverCloudGenerator.zip /tmp/QEverCloudGenerator_windows_x86.zip
-          gh release upload --clobber ${TAG_NAME} /tmp/QEverCloudGenerator_windows_x86.zip -R d1vanov/QEverCloudGenerator
+          for i in 0..3
+          do
+            export UPLOADED=0
+            gh release upload --clobber ${TAG_NAME} /tmp/QEverCloudGenerator_windows_x86.zip -R d1vanov/QEverCloudGenerator && export UPLOADED=1 || true
+            if [ "$UPLOADED" = "1" ]; then
+              break
+            fi
+          done
+          if [ "$UPLOADED" != "1" ]; then
+            echo "Failed to upload artifact to release"
+            exit 1
+          fi
         if: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/development' }}
+        shell: bash
 
       - name: Upload Windows x64 artifact to tagged release
         id: upload_windows_x64_artifact_to_tagged_release
@@ -474,5 +606,17 @@ jobs:
         run: |
           export TAG_NAME=$(echo $GITHUB_REF | sed 's/.*\/\(.*\)$/\1/')
           mv $GITHUB_WORKSPACE/artifacts/windows/x64/QEverCloudGenerator.zip /tmp/QEverCloudGenerator_windows_x64.zip
-          gh release upload --clobber ${TAG_NAME} /tmp/QEverCloudGenerator_windows_x64.zip -R d1vanov/QEverCloudGenerator
+          for i in 0..3
+          do
+            export UPLOADED=0
+            gh release upload --clobber ${TAG_NAME} /tmp/QEverCloudGenerator_windows_x64.zip -R d1vanov/QEverCloudGenerator && export UPLOADED=1 || true
+            if [ "$UPLOADED" = "1" ]; then
+              break
+            fi
+          done
+          if [ "$UPLOADED" != "1" ]; then
+            echo "Failed to upload artifact to release"
+            exit 1
+          fi
         if: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/development' }}
+        shell: bash
