Update GitHub build and deploy workflow

diff --git a/.github/workflows/build_and_deploy.yml b/.github/workflows/build_and_deploy.yml
--- a/.github/workflows/build_and_deploy.yml
+++ b/.github/workflows/build_and_deploy.yml
@@ -41,6 +41,7 @@ jobs:
       - name: Install non-Qt dependencies
         id: install_non_qt_deps
         run: |
+          sudo apt-get -qq update
           sudo apt-get -qq install cmake ninja-build p7zip-full coreutils curl
 
       - name: Install gcc
@@ -307,8 +308,24 @@ jobs:
           if [ "${exit_status}" = 0 ]; then
             export COMMIT_SHA=$(cat /tmp/gh_get_release.json | jq '.target_commitish');
             if ! [ "${COMMIT_SHA}" = "${GITHUB_SHA}" ]; then
-              gh release delete continuous-${BRANCH_NAME} -y -R d1vanov/QEverCloudGenerator;
-              curl -X DELETE -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/d1vanov/QEverCloudGenerator/git/refs/tags/continuous-${BRANCH_NAME};
+              export PREVIOUS_CONTINUOUS_RELEASE_DELETED=0
+              for i in {1..10}
+              do
+                echo "Trying to delete previous continuous release continuous-${BRANCH_NAME}"
+                gh release delete continuous-${BRANCH_NAME} -y -R d1vanov/QEverCloudGenerator;
+                curl -X DELETE -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/d1vanov/QEverCloudGenerator/git/refs/tags/continuous-${BRANCH_NAME};
+                gh api /repos/d1vanov/QEverCloudGenerator/releases/tags/continuous-${BRANCH_NAME} > /tmp/gh_get_release.json && exit_status=$? || exit_status=$?
+                if [ "${exit_status}" != 0 ]; then
+                  echo "It appears that previous continuous release is deleted now"
+                  export PREVIOUS_CONTINUOUS_RELEASE_DELETED=1
+                  break
+                fi
+                echo "Was able to receive information about the attempted to be deleted previous continuous release, waiting for 5 seconds before the next attempt"
+                sleep 5
+              done
+              if [ "$PREVIOUS_CONTINUOUS_RELEASE_DELETED" != "1" ]; then
+                echo "Failed to delete previous continuous release after several attempts!"
+              fi
             fi
           fi
         shell: bash
@@ -316,38 +333,28 @@ jobs:
       - name: Create new continuous master release
         id: create_new_continuous_master_release
         if: ${{ github.ref == 'refs/heads/master' }}
-        uses: actions/create-release@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          tag_name: continuous-master
-          release_name: Continuous build (continuous-master)
-          draft: false
-          prerelease: true
+        run: |
+          gh release create continuous-master --draft=false --prerelease --title "Continuous build (continuous-master)" --target $GITHUB_SHA -R d1vanov/QEverCloudGenerator
 
       - name: Create new continuous development release
         id: create_new_continuous_development_release
         if: ${{ github.ref == 'refs/heads/development' }}
-        uses: actions/create-release@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          tag_name: continuous-development
-          release_name: Continuous build (continuous-development)
-          draft: false
-          prerelease: true
+        run: |
+          gh release create continuous-development --draft=false --prerelease --title "Continuous build (continuous-development)" --target $GITHUB_SHA -R d1vanov/QEverCloudGenerator
 
       - name: Create new tagged release
         id: create_new_tagged_release
         if: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/development' }}
-        uses: actions/create-release@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          tag_name: ${{ github.ref }}
-          release_name: Release build (${{ github.ref }})
-          draft: false
-          prerelease: false
+          GITHUB_REF: ${{ github.ref }}
+          GITHUB_REF_NAME: ${{ github.ref_name }}
+        run: |
+          gh release create "$GITHUB_REF" --draft=false --title "Release build ($GITHUB_REF_NAME)" --target $GITHUB_SHA -R d1vanov/QEverCloudGenerator
 
       - name: Download linux artifact
         id: download_linux_artifact
